### PR TITLE
fix(cxx_indexer): emit ref to class from ctor

### LINKED ISSUE #4381: include class ctors in references for the class itself
When looking at references and definitions of a class, Kythe currently returns:
```
struct [[Foo]] {
   Foo();
   Foo(const [[Foo]]&);
   ~[[Foo]]();
};
```
This is suboptimal if one is looking to rename a class, for example.  Following the example with the destructor, the constructor should have a ref to the class name which overlaps the defines/binding edge for the ctor.  I believe these were inhibited prior due to poor UI/client support for overlapping ranges, but this handling is much better now.

### PR DESCRIPTION
**Pull request by shahms**
This fixes #4381.

### CODE REVIEW

File: kythe/cxx/indexer/cxx/IndexerASTHooks.cc [hunk 1]
```diff
@@ -1077,6 +1077,21 @@ void IndexerASTVisitor::VisitRecordDeclComment(
   }
 }
 
+bool IndexerASTVisitor::TraverseCXXConstructorDecl(
+    clang::CXXConstructorDecl* CD) {
+  LOG(ERROR) << DumpString(*CD);
```
Comment (jaysachs) [inline kythe/cxx/indexer/cxx/IndexerASTHooks.cc]: remove

Comment (shahms) [reply kythe/cxx/indexer/cxx/IndexerASTHooks.cc]: Gah, thanks!
